### ISSUE TITLE
Email Error From View Topic

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/phpBB2x#14]
When clicking the email icon to email a member of the board, the following error pops up.

>Warning: Undefined variable $error in C:\xxxxxxx\xxxxxxx\xxxxxxxx\includes\usercp_email.php on line 167

Offending line:  `if ( $error )`

**Comment by IntegraMOD** [comment]
$error = '';
            if ( $error )

**Comment by MWE001** [comment]
Parse error: Unmatched '}' in C:\xxxxxxx\xxxxxx\xxxxxxx\includes\usercp_email.php on line 210
