### ISSUE TITLE
Install Warning

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/phpBB2x#16]
Warning: Constant DEBUG already defined in C:\xxxxx\www\xxxxx\ixxxxxxx\constants.php on line 29 

Just a warning. Everything runs fine.

**Comment by MWE001** [comment]
Oh but it stays on top of the board even after install.

**Comment by IntegraMOD** [comment]
if this is after the latest updated install.php, you can remove debug from constants php as install now writes it to config.php
it defaults to off
