### ISSUE TITLE
Word Censors Causing Blank Forums

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/phpBB2x#5]
I setup a few replacement words for Word Censoring. When I went to my forum and tested and I used the words to be replaced, It showed as it should on the index and on the view forum. As soon as we get to the viewtopic, the post is missing. All of the rest of the page is there except the post. I checked the db and it was written to the database without the words being replaced.

Now heading back to the ACP/General Admin/Word Censors, I delete the 2 words I wanted filtered and changed. I go back to the forum to make a new post and my post I just made that was missing is now magically back.

**Comment by IntegraMOD** [comment]
I updated viewtopic.php can you confirm its working on your stack?

**Comment by MWE001** [comment]
Please see the other issue regarding php version. But yes, I will go give it a look real quick.

**Comment by MWE001** [comment]
That fix fixed it. It now works as it should.  However, once again, please take note of the other issue thread where I mention the php thing I have going on. I am working on it as we speak. Should be pretty quick and Ill have it sorted out.

**Comment by IntegraMOD** [comment]
I believe i pushed the fix for the other error

**Comment by MWE001** [comment]
I am now 100% on php 8.3 and I can confirm it works 100% on my stack now. Ill go take a peak at the others as well.

**Comment by MWE001** [comment]
I'll close this one out now since the fix Helter provided worked out. I have tested on 3 installs now and all 3 work just fine in every which way I could possibly test and we all know how my testing goes.
