### ISSUE TITLE
admin_db_utilities error

### ISSUE THREAD

**Issue by MWE001** [IntegraMOD/phpBB2x#8]
I am pretty sure the commit I sent up fixes 1 preg error when restoring the db via the ACP. However there is another issue.

When restoring the db using an ACP created DB backup, I get the following when trying to restore using said file:

General Error
Error importing backup file

DEBUG MODE

SQL Error : 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '

( ! ) Notice: Undefined variable: index in C:\xxxxx\xxxxx\xxxxxxxx\admin\admin_db_utilities.php on line 425
Call Stack
#	Time	Memory	Function	Location
1	0.0003	370144	{main}( )	...\admin_db_utilities.php:0
2	2.0434	600056	get_table_def_mysql( $table = '

Line : 984
File : admin_db_utilities.php

Now that being said, If I create my own db backup using phpmyadmin and restore the db using that file in the restore db in the ACP it works just fine. No error at all.

**Comment by IntegraMOD** [comment]
winmerge shows you did your edit a little different than mine. try it now. my localhost is working without error

**Comment by IntegraMOD** [comment]
interesting.. looking at the file history here, our edits are the same. Still, I cant reproduce your error on localhost (mysql strict/php8.3.9)

**Comment by MWE001** [comment]
Well, we are not going to believe this one. First off I must apologize. I was on php 7.4 not 8.3  However, for some strange reason I set the virtual host up to run FCGI -> PHP 8.3.6   As soon as I switch over to php version 8.3 I immediately got the TEMPLATE_CONFIG error from BS_subSIlver. 

I would toss out this one for now. I am positive this is 100% on my end as far as I can tell. I am not sure how or why I did what i did here. I have never done that ever before.  Let me get things straight on my end before I resume or go any further.  Sorry about that hassle man. I am sitting here shaking my head as I type.

**Comment by IntegraMOD** [comment]
no worries. These were still errors that needed resolution. The current git should resolve the errors in php8.
The TEMPLATE_CONFIG error though means your files are not current. If your on git desktop you should have a pull notice to update your local repository

**Comment by MWE001** [comment]
I synced my form as well as did a fetch a bit ago and I am attempting a 100% clean install with fresh files so we are on the same page. I am 100% striking out on the install file again. 

Just a quick note and this has nothing to do with this issue on this thread (Install File failing  errors)

______________________________________________________________________________________________________-

Undefined variable $lang install.php on line 206
Uncaught Error: Call to undefined function each()  install.php on line 635

Of all the install files I have, none will let me get by this issue. Strict mode is shut 100% off.

**Comment by MWE001** [comment]
I am back to square 1 with all the errors that I originally had now using the updated fetch from Git. 

php version 8.3.6   MySQL  8.3.0

**Comment by IntegraMOD** [comment]
I just pushed the last install.php that I used. Let me know it you have the same issues. It was mostly just formatting fixes but there are a few small differences

**Comment by MWE001** [comment]
I ran through the file and fixed everything I could but 1 small issue and it installed flawless. I will grab the one you just pushed and do another install not a problem at all. 

I have 1 more error in the database utilities still.
![Screenshot_3](https://github.com/user-attachments/assets/798fa6d1-3eea-40cf-801f-e8a9ff095545)

**Comment by IntegraMOD** [comment]
sorry Ray. I cant access the work site yet until webuzo fixes the license problem. As best I can tell the last posted install.php was the one I uploaded but I made some edits to it online. I just updated install.php again with the edits I could find from the history cache. There may be slight differences but I wont  be able to check until ftp is back online.

**Comment by MWE001** [comment]
Its all good no worries at all. I am taking this time to do a solid once over of the stack. I had a 100% complete mess going on. WAY too many virtual hosts to keep track of. It was getting way out of hand for me. If I can't line it out a little better (error reporting wise) I think it is time I jump on the stack that you are using. I know for 100% certain I have strict mode disabled and yet I am showing warnings, notices and all regardless. I hate to report and alter files and have you and Ven chase your tails over something that may be as simple as a stack issue on my end.  We know WAMP has a mind of it's own when it wants to. 

I'll stand by for now and do some house keep on the hard drive and get up and go do some walking with the dogs for a bit. :-)

**Comment by MWE001** [comment]
This is literally the last of the problem children.  The install file the way you merged it no longer has any errors on the initial install page and now instead of an entire page of errors after information submissions, it only has this one and it happens to be the only 1 that I could not fix earlier today. I tried to cheat and look at IM 151 install file and that line does not even exist. Not even close. I know the answer to this one but it is eluding me as we speak so I'll just leave it right here and not mess it up any more. :-)

`foreach($update_config as list ($config_name => $config_value))`  Line 881 Undefined Variable $config_name

**Comment by IntegraMOD** [comment]
try replacing that line with this
`foreach($update_config as list ($config_name => $config_value))`

**Comment by IntegraMOD** [comment]
try replacing that line with this
`foreach($update_config as ($config_name => $config_value))`

**Comment by MWE001** [comment]
Will do. I'll report back.

**Comment by IntegraMOD** [comment]
im having weird clipboard issues. basically your just dropping the "list"

**Comment by MWE001** [comment]
Im going to check it out here in a few minutes and see how it goes. I was working on a quick issue server side and got it straight. Now I see a PM issue I am going to post so I don't forget it.

**Comment by MWE001** [comment]
> foreach($update_config as ($config_name => $config_value))

Parse error: syntax error, unexpected token "=>" in C:\xxx\xxxx\xxxxx\install\install.php on line 881

**Comment by MWE001** [comment]
Now all the previous errors that I reported on this are no longer kicking off however there is another that it may be associated with. 

Now when I attempt to do a backup of any type from the db manager in ACP, it tells me to standby the download will be ready in a minute and then after af ew seconds it goes to File Not Found error and give a great big long link to where it believes the file should be.

I'll post that link on the main website if interested since we are still working on it for security issues (??). I would rather not here unless you feel as though it is ok.

**Comment by MWE001** [comment]
This is a browser issue not a Software issue. Thanks for the reminder of HTTPS.
